# =============================================================================
# Google Cloud Build Configuration for Timeto Application
# =============================================================================
# This file automates building and deploying to Cloud Run
#
# Trigger this build manually:
#   gcloud builds submit --config cloudbuild.yaml
#
# Or set up a trigger in Cloud Console for automatic deployments

substitutions:
  _REGION: me-west1  # Tel Aviv region for Israel
  _API_SERVICE_NAME: timeto-api
  _CLIENT_SERVICE_NAME: timeto-client
  _GCS_BUCKET: ${PROJECT_ID}-timeto-uploads

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ==========================================================================
  # Step 1: Build API Docker image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:latest'
      - '-f'
      - 'server/Dockerfile.cloudrun'
      - './server'

  # ==========================================================================
  # Step 2: Build Client Docker image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-client'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:latest'
      - '-f'
      - 'client/Dockerfile.cloudrun'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://${_API_SERVICE_NAME}-${PROJECT_NUMBER}.${_REGION}.run.app'
      - './client'

  # ==========================================================================
  # Step 3: Push API image to Container Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:${SHORT_SHA}'
    waitFor:
      - 'build-api'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-latest'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:latest'
    waitFor:
      - 'build-api'

  # ==========================================================================
  # Step 4: Push Client image to Container Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-client'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:${SHORT_SHA}'
    waitFor:
      - 'build-client'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-client-latest'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:latest'
    waitFor:
      - 'build-client'

  # ==========================================================================
  # Step 5: Deploy API to Cloud Run
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=prod,PORT=8080,GCS_BUCKET_NAME=${_GCS_BUCKET}'
      - '--set-secrets'
      - 'MONGO_URI=MONGO_URI:latest,JWT_SECRET=JWT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest,EMAIL_USER=EMAIL_USER:latest,EMAIL_PASS=EMAIL_PASS:latest,SENTRY_DSN=SENTRY_DSN:latest'
    waitFor:
      - 'push-api'
      - 'push-api-latest'

  # ==========================================================================
  # Step 6: Get API URL and deploy Client
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the API service URL
        API_URL=$(gcloud run services describe ${_API_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        echo "API URL: $$API_URL"
        
        # Deploy client with API URL
        gcloud run deploy ${_CLIENT_SERVICE_NAME} \
          --image gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --port 8080 \
          --set-env-vars "REACT_APP_API_URL=$$API_URL"
    waitFor:
      - 'deploy-api'
      - 'push-client'
      - 'push-client-latest'

  # ==========================================================================
  # Step 7: Output deployment information
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'output-urls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "Deployment Complete!"
        echo "=========================================="
        echo ""
        echo "API Service URL:"
        gcloud run services describe ${_API_SERVICE_NAME} --region=${_REGION} --format='value(status.url)'
        echo ""
        echo "Client Service URL:"
        gcloud run services describe ${_CLIENT_SERVICE_NAME} --region=${_REGION} --format='value(status.url)'
        echo ""
        echo "=========================================="

images:
  - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_API_SERVICE_NAME}:latest'
  - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_CLIENT_SERVICE_NAME}:latest'

timeout: '1800s'  # 30 minutes timeout

